
DROP TABLE IF EXISTS "trips" CASCADE;
DROP TABLE IF EXISTS "transfers" CASCADE;
DROP TABLE IF EXISTS "stops" CASCADE;
DROP TABLE IF EXISTS "stop_times" CASCADE;
DROP TABLE IF EXISTS "shapes" CASCADE;
DROP TABLE IF EXISTS "routes" CASCADE;
DROP TABLE IF EXISTS "calendar" CASCADE;
DROP TABLE IF EXISTS "calendar_dates" CASCADE;
DROP TABLE IF EXISTS "agency" CASCADE;